### ISSUE TITLE
Snippets missing

### ISSUE THREAD

**Issue by nbussman** [myEditor/myLaTeX-syntax#1]
Hi,
it would be awesome to find some more snippets like documentclass, usepackage, maketitle, tableofcontents etc.

Cheers Nils

**Comment by torn4dom4n** [comment]
@nbussman Sorry for the delay. I need more information about snippets what you want!

**Comment by torn4dom4n** [comment]
I tried to find more snippets like [sublimehq](https://github.com/sublimehq/Packages) but my package has all snippets. If you want more, you can reopen this issue with a link. Thanks.
